version: '3.8'

services:
  app:
    expose:
      - "9000"
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 2.5g 
    networks:
      - backend-net
      - internal

  db:
    expose:
      - "3306"
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 2.5g 
    networks:
      - internal

  web:
    networks:
      - internal
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 2.5g  
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      # Conf middlewares
      - "traefik.http.middlewares.auth-${COMPOSE_PROJECT_NAME}.basicauth.users=${COMPOSE_PROJECT_NAME}:$$apr1$$ytUC9EcZ$$u3b/D2cTP7ithPcdeIYRX0"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}Header.headers.framedeny=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}Header.headers.browserxssfilter=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}Header.headers.customFrameOptionsValue=sameorigin"
      # Conf router https
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-websecure.rule=Host(`${HOST}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-websecure.priority=99"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-websecure.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-websecure.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-websecure.tls.certresolver=default"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-websecure.tls.options=intermediate@file"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-websecure.middlewares=auth-${COMPOSE_PROJECT_NAME},${COMPOSE_PROJECT_NAME}Header,compress@file"
      # Conf router http
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-web.rule=Host(`${HOST}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-web.priority=98"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-web.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-web.middlewares=auth-${COMPOSE_PROJECT_NAME},redirect-to-https,${COMPOSE_PROJECT_NAME}Header,compress@file"


  db_test:
    image: mysql:8.0
    container_name: ${COMPOSE_PROJECT_NAME}_db_test
    hostname: ${COMPOSE_PROJECT_NAME}_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}_test
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data_test:/var/lib/mysql
    networks:
      - internal

  mailpit:
    image: axllent/mailpit:v1.20.5
    container_name: ${COMPOSE_PROJECT_NAME}_mailpit
    restart: unless-stopped
    volumes:
      - mp_data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_UI_AUTH: "mailpit:preview"
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    #1026 & 8026 Host port is already in use for engage_mailpit on server
    #1027 & 8027 Host port is already in use for unis_mailpit on server
    #1028 & 8028 Host port is already in use for infoafrica_mailpit on server
    #ports:
      #- 1029:1025
      #- 8029:8025 ## To be use from external accèes to mailpit
    expose:
      - 8025
      - 1025
    networks:
      - traefik_net
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true'
      - "traefik.http.services.${MAILPIT_PROJECT_NAME}.loadbalancer.server.port=8025"
      ### conf router HTTPS
      - 'traefik.http.routers.${MAILPIT_PROJECT_NAME}-websecure.rule=Host(`${MP_HOST}`)'
      - 'traefik.http.routers.${MAILPIT_PROJECT_NAME}-websecure.entrypoints=websecure'
      - 'traefik.http.routers.${MAILPIT_PROJECT_NAME}-websecure.tls=true'
      - 'traefik.http.routers.${MAILPIT_PROJECT_NAME}-websecure.tls.certresolver=default'
      - 'traefik.http.routers.${MAILPIT_PROJECT_NAME}-websecure.tls.options=intermediate@file'
      - 'traefik.http.routers.${MAILPIT_PROJECT_NAME}-websecure.middlewares=redirect-to-https'
      - 'traefik.http.routers.${MAILPIT_PROJECT_NAME}-websecure.service=${MAILPIT_PROJECT_NAME}'
      ### conf router HTTP
      - "traefik.http.routers.${MAILPIT_PROJECT_NAME}-web.rule=Host(`${MP_HOST}`)"
      - "traefik.http.routers.${MAILPIT_PROJECT_NAME}-web.priority=98"
      - "traefik.http.routers.${MAILPIT_PROJECT_NAME}-web.entrypoints=web"
      - "traefik.http.routers.${MAILPIT_PROJECT_NAME}-web.middlewares=redirect-to-https,compress@file"



  composer:
    container_name: ${COMPOSE_PROJECT_NAME}_composer
    image: fulldigits/composer:7.4-composerv2
    volumes:
      - ../:/app
      - composer-caches:/var/cache
      - ${KEY_PATH}:/root/.ssh/id_ed25519
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 2.5g
    command: >
      /bin/sh -c "echo '--- Install main dependencies ---'
      && chmod 700 /root/.ssh/id_ed25519
      && touch /root/.ssh/known_hosts
      && ssh-keyscan bitbucket.org >> /root/.ssh/known_hosts
      && composer install -vvv && tail -f /dev/null"

  yarn:
    image: fulldigits/yarn:node-10
    container_name: ${COMPOSE_PROJECT_NAME}_yarn
    working_dir: /var/app
    volumes:
        - ../.env:/var/.env
        - ../.git:/var/.git
        - ../web/app/themes/cneai/:/var/app
    environment:
        - YARN_CACHE_FOLDER=/var/cache/yarn
        - APP_CONTAINER=cneai_web
        - BROWSERSYNC_PORT=${BROWSERSYNC_PORT}
        - BROWSERSYNC_PORT_UI=${BROWSERSYNC_PORT_UI}
        - HOT_RELOAD_PORT=${HOT_RELOAD_PORT}
    ports:
        - ${BROWSERSYNC_PORT}:${BROWSERSYNC_PORT}
        - ${BROWSERSYNC_PORT_UI}:${BROWSERSYNC_PORT_UI}
        - ${HOT_RELOAD_PORT}:${HOT_RELOAD_PORT}
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 2.5g



  phpmyadmin_test:
    image: phpmyadmin/phpmyadmin
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin_test
    hostname: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db_test
      PMA_PORT: 3306
      PHP_INI_UPLOAD_MAX_FILESIZE: 64M
      PHP_INI_POST_MAX_SIZE: 64M
      UPLOAD_LIMIT: 64M
    depends_on:
      - db_test
    networks:
      - internal
      - traefik_net

volumes:
  data:
    name: ${COMPOSE_PROJECT_NAME}-database

  mp_data:
    name: ${COMPOSE_PROJECT_NAME}_mp_data

  composer-caches:
    name: ${COMPOSE_PROJECT_NAME}-composer-caches

  db_data_test:
    name: ${COMPOSE_PROJECT_NAME}_db_data_test


networks:
  internal:
      name: ${COMPOSE_PROJECT_NAME}_internal
      internal: true
  traefik_net:
      external:
          name: traefik_net
