version: '3.8'

services:

  app:
    image: fulldigits/php:8.3-alpine-xdebug
    container_name: ${COMPOSE_PROJECT_NAME}_app
    hostname: ${COMPOSE_PROJECT_NAME}_app
    volumes:
      - ./etc/php/www.conf:/usr/local/etc/php-fpm.d/zz-custom.conf
      - ./etc/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ..:/var/www/html
    networks:
      - internal

  db:
    image: mysql:8.0
    container_name: ${COMPOSE_PROJECT_NAME}_db
    hostname: ${COMPOSE_PROJECT_NAME}_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal

  web:
    image: fulldigits/apache:2.4-secure
    container_name: ${COMPOSE_PROJECT_NAME}_web
    hostname: ${COMPOSE_PROJECT_NAME}_web
    volumes:
      - ../:/var/www/html
      - ./etc/apache/000-default.conf:/usr/local/apache2/conf.d/000-default.conf
    environment:
      APACHE_SERVER_NAME: ${HOST}
      APACHE_BACKEND_HOST: ${SERVER_PHP}
    networks:
      - internal
      - traefik_net

  redis:
    image: redis:latest
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    hostname: ${COMPOSE_PROJECT_NAME}_redis

    networks:
      - internal
      - traefik_net

volumes:
  db_data:
    name: ${COMPOSE_PROJECT_NAME}_db_data
    
networks:   
  internal:
    name: ${COMPOSE_PROJECT_NAME}_internal
    internal: true         
          
  traefik_net:
      external:
          name: traefik_net
  backend-net:
      external:
          name: backend-net