version: '3.8'

services:

  app:
    volumes:
      - ../:/var/www/html
      - /home/${COMPOSE_PROJECT_NAME}-shu/${COMPOSE_PROJECT_NAME}.docker.site-check.me/shared:/home/${COMPOSE_PROJECT_NAME}-shu/${COMPOSE_PROJECT_NAME}.docker.site-check.me/shared
    expose:
      - "9000"
    networks:
      - internal 
      - backend-net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 2.5g 

  web:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      # Conf middlewares
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}Header.headers.framedeny=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}Header.headers.browserxssfilter=true"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}Header.headers.customFrameOptionsValue=sameorigin"

      # Conf router https
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-websecure.rule=Host(`${HOST}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-websecure.priority=99"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-websecure.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-websecure.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-websecure.tls.certresolver=default"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-websecure.tls.options=intermediate@file"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-websecure.middlewares=${COMPOSE_PROJECT_NAME}Header,compress@file"

      # Conf router http
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-web.rule=Host(`${HOST}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-web.priority=98"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-web.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-web.middlewares=compress@file"



    restart: unless-stopped
    volumes:
      - /home/${COMPOSE_PROJECT_NAME}-shu/${COMPOSE_PROJECT_NAME}.docker.site-check.me/shared:/home/${COMPOSE_PROJECT_NAME}-shu/${COMPOSE_PROJECT_NAME}.docker.site-check.me/shared

    expose:
      - "80"
      - "443"

    networks:
      - internal
      - traefik_net
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 2.5g 

    links:
      - app
      - db

  db:
    expose:
      - "3306"
    restart: unless-stopped
    networks:
      internal: null
      phpmyadmin_pma-net: null
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 2.5g 

networks:
  internal:
    name: ${COMPOSE_PROJECT_NAME}-internal
    internal: true

  traefik_net:
    external:
      name: traefik_net
  backend-net:
    external:
      name: backend-net

  phpmyadmin_pma-net:
      external:
          name: phpmyadmin_pma-net