name: Auto Create Pull Request

on:
  push:
    branches-ignore:
      - main  

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: ${{ github.ref_name }} 
          base: develop 
          title: "Auto PR: Merge ${{ github.ref_name }} into develop"
          body: "PR generated automatically : `${{ github.ref_name }}`."
          draft: false 
          assignees: ${{ github.actor }} 
